[package]
name = "search_in_a_binary_search_tree"
version = "0.1.0"
authors = ["DeveloperC <DeveloperC@protonmail.com>"]
edition = "2021"


[dependencies]


[dev-dependencies]
# For snapshot testing.
insta = "=1.46.2"
