[package]
name = "reverse_linked_list"
version = "0.1.0"
authors = ["DeveloperC <DeveloperC@protonmail.com>"]
edition = "2021"


[dependencies]


[dev-dependencies]
# For snapshot testing.
insta = "=1.44.2"
